# -*- coding: utf-8 -*-
"""Efficience

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIh-7NaGFmsPlT3Lm0lei7okVFD2LveI
"""

!pip install openpyxl
import pandas as pd
from google.colab import files

# Télécharger ton fichier Excel
uploaded = files.upload()

# Remplace 'nom_de_ton_fichier.xlsx' par le nom de ton fichier Excel téléchargé
df = pd.read_excel('LIST.xlsx', engine='openpyxl')

# Affiche les 5 premières lignes de tes données pour vérifier
df.head()

# Vérifie les types de données dans le DataFrame
df.dtypes

# Convertir la colonne 'NB PERSONNES' en numérique (entiers)
df['NB PERSONNES'] = pd.to_numeric(df['NB PERSONNES'], errors='coerce')

# Convertir la colonne 'TEMPS CYCLE' en numérique (entiers)
df['TEMPS CYCLE'] = pd.to_numeric(df['TEMPS CYCLE'], errors='coerce')

import pandas as pd

# Exemple de DataFrame après avoir nettoyé les données (assurez-vous que vos colonnes sont numériques)
# df = pd.read_excel("path_to_your_data.xlsx")

# Calculer l'efficience par famille
df['Efficience (%)'] = ((40 * df['WSD']) / (df['NB PERSONNES'] * 460))*100

# Grouper les données par famille et calculer la moyenne de l'efficience pour chaque famille
efficience_par_famille = df.groupby('FAMILLE')['Efficience (%)'].mean().reset_index()

# Afficher les résultats
efficience_par_famille.head()

!pip install plotly

import plotly.graph_objects as go

# Créer une liste des jauges pour chaque famille
fig = go.Figure()

for i, row in efficience_par_famille.iterrows():
    fig.add_trace(go.Indicator(
        mode="gauge+number",
        value=row['Efficience (%)'],
        title={"text": f"Famille: {row['FAMILLE']}"},
        gauge={
            "axis": {"range": [0, 100]},
            "bar": {"color": "darkblue"},
            "steps": [
                {"range": [0, 40], "color": "red"},
                {"range": [40, 70], "color": "yellow"},
                {"range": [70, 100], "color": "green"}
            ]
        }
    ))

# Mettre en forme le tableau de bord
fig.update_layout(
    title="Tableau de bord de l'efficience par famille",
    grid={'rows': len(efficience_par_famille), 'columns': 1},
    height=500 * len(efficience_par_famille),
    showlegend=False
)

# Afficher le tableau de bord
fig.show()

!pip install dash

import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go
import pandas as pd

# Initialiser l'application Dash
app = dash.Dash(__name__)

# Exemple de données (tu peux remplacer cela par tes propres données)
df = pd.DataFrame({
    'FAMILLE': ['Famille A', 'Famille B', 'Famille C'],
    'Efficience (%)': [85, 65, 92]
})

# Créer une figure de graphiques en jauge
fig = go.Figure()

for i, row in df.iterrows():
    fig.add_trace(go.Indicator(
        mode="gauge+number",
        value=row['Efficience (%)'],
        title={"text": f"Famille: {row['FAMILLE']}"},
        gauge={
            "axis": {"range": [0, 100]},
            "bar": {"color": "darkblue"},
            "steps": [
                {"range": [0, 40], "color": "red"},
                {"range": [40, 70], "color": "yellow"},
                {"range": [70, 100], "color": "green"}
            ]
        }
    ))

# Mettre en forme la disposition du tableau de bord
app.layout = html.Div([
    html.H1("Tableau de bord de l'efficience par famille"),
    dcc.Graph(figure=fig)
])

# Exécuter l'application Dash
if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)

!pip install dash

import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go
import pandas as pd

# Initialiser l'application Dash
app = dash.Dash(__name__)

# Exemple de données (remplace ceci par tes propres données)
df = pd.DataFrame({
    'FAMILLE': ['Famille A', 'Famille B', 'Famille C'],
    'Efficience (%)': [85, 65, 92]
})

# Créer la figure des jauges
fig = go.Figure()

# Créer une jauge pour chaque famille
for i, row in df.iterrows():
    fig.add_trace(go.Indicator(
        mode="gauge+number",
        value=row['Efficience (%)'],
        title={"text": f"Famille: {row['FAMILLE']}"},
        gauge={
            "axis": {"range": [0, 100]},  # Plage de la jauge
            "bar": {"color": "darkblue"},
            "steps": [
                {"range": [0, 40], "color": "red"},
                {"range": [40, 70], "color": "yellow"},
                {"range": [70, 100], "color": "green"}
            ]
        }
    ))

# Disposition du tableau de bord
app.layout = html.Div([
    html.H1("Tableau de bord de l'efficience par famille"),
    dcc.Graph(figure=fig)
])

# Lancer l'application Dash
if __name__ == '__main__':
    app.run_server(debug=True)

